SQUID_FILTERWHEEL_MAX_INDEX = 8
SQUID_FILTERWHEEL_MIN_INDEX = 1
SQUID_FILTERWHEEL_OFFSET = 0.008 * 100

OBJECTIVE_SWITCH_MAX_INDEX = 3
OBJECTIVE_SWITCH_MIN_INDEX = 0
OBJECTIVE_HOLES = 4
OBJECTIVE_GEAR_LARGE = 132.0
OBJECTIVE_GEAR_SMALL = 48.0
OBJECTIVE_RATIO = OBJECTIVE_GEAR_LARGE / OBJECTIVE_GEAR_SMALL
SCREW_PITCH_W_MM = 1


class AXIS:
    """协议轴值（与旧 Squid AXIS 类一致）"""
    X  = 0
    Y  = 1
    Z  = 2
    XY = 4   # 联合归位专用
    W  = 5
    W2 = 6


class LIMIT_CODE:
    """SET_LIM 命令的限位码（与固件 commandprocessor.cpp LIM_CODE_* 一致）"""
    X_POSITIVE = 0
    X_NEGATIVE = 1
    Y_POSITIVE = 2
    Y_NEGATIVE = 3
    Z_POSITIVE = 4
    Z_NEGATIVE = 5


# 轴名称 → (正向限位码, 负向限位码) 映射
AXIS_LIMIT_CODE_MAP = {
    "X": (LIMIT_CODE.X_POSITIVE, LIMIT_CODE.X_NEGATIVE),
    "Y": (LIMIT_CODE.Y_POSITIVE, LIMIT_CODE.Y_NEGATIVE),
    "Z": (LIMIT_CODE.Z_POSITIVE, LIMIT_CODE.Z_NEGATIVE),
}


class CMD_SET:
    # 相对移动命令
    MOVE_X = 0
    MOVE_Y = 1
    MOVE_Z = 2
    MOVE_THETA = 3
    MOVE_W = 4

    # 绝对移动命令
    MOVETO_X = 6
    MOVETO_Y = 7
    MOVETO_Z = 8
    MOVETO_W = 18

    # 归位命令
    HOME_OR_ZERO = 5

    # 限位设置
    SET_LIM = 9
    SET_LIM_SWITCH_POLARITY = 20

    # 照明控制
    TURN_ON_ILLUMINATION = 10
    TURN_OFF_ILLUMINATION = 11
    SET_ILLUMINATION = 12
    SET_ILLUMINATION_LED_MATRIX = 13
    SET_ILLUMINATION_INTENSITY_FACTOR = 17

    # 硬件配置
    ACK_JOYSTICK_BUTTON_PRESSED = 14
    ANALOG_WRITE_ONBOARD_DAC = 15
    SET_DAC80508_REFDIV_GAIN = 16
    CONFIGURE_STEPPER_DRIVER = 21
    SET_MAX_VELOCITY_ACCELERATION = 22
    SET_LEAD_SCREW_PITCH = 23
    SET_OFFSET_VELOCITY = 24

    # PID 控制
    CONFIGURE_STAGE_PID = 25
    ENABLE_STAGE_PID = 26
    DISABLE_STAGE_PID = 27
    SET_PID_ARGUMENTS = 29

    # 其他
    SET_HOME_SAFETY_MERGIN = 28
    SEND_HARDWARE_TRIGGER = 30
    SET_STROBE_DELAY = 31
    SET_AXIS_DISABLE_ENABLE = 32
    SET_TRIGGER_MODE = 33

    # 多端口照明命令（v1.0+）
    SET_PORT_INTENSITY = 34
    TURN_ON_PORT = 35
    TURN_OFF_PORT = 36
    SET_PORT_ILLUMINATION = 37
    SET_MULTI_PORT_MASK = 38
    TURN_OFF_ALL_PORTS = 39

    SET_PIN_LEVEL = 41

    # 初始化和重置
    INITFILTERWHEEL = 253
    INITIALIZE = 254
    RESET = 255


# 轴名称到相对移动命令的映射
# 注意：命令码与轴索引不是简单的加法关系
AXIS_MOVE_CMD_MAP = {
    "X": CMD_SET.MOVE_X,      # 0
    "Y": CMD_SET.MOVE_Y,      # 1
    "Z": CMD_SET.MOVE_Z,      # 2
    "W": CMD_SET.MOVE_W,      # 4
    "E1": CMD_SET.MOVE_W,     # 4 (E1 使用与 W 相同的命令，通过轴索引区分)
    "E3": CMD_SET.MOVE_Z,     # 2 (E3 使用与 Z 相同的命令，通过轴索引区分)
    "E4": CMD_SET.MOVE_W,     # 4 (E4 使用与 W 相同的命令，通过轴索引区分)
}

# 轴名称到绝对移动命令的映射
AXIS_MOVETO_CMD_MAP = {
    "X": CMD_SET.MOVETO_X,    # 6
    "Y": CMD_SET.MOVETO_Y,    # 7
    "Z": CMD_SET.MOVETO_Z,    # 8
    "W": CMD_SET.MOVETO_W,    # 18
    "E1": CMD_SET.MOVETO_W,   # 18
    "E3": CMD_SET.MOVETO_Z,   # 8
    "E4": CMD_SET.MOVETO_W,   # 18
}
